spring.application.name=rcpdv
spring.datasource.url=jdbc:postgresql://localhost:5432/ferragista_pdv
spring.datasource.username=postgres
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=update
server.port=8080